### ISSUE TITLE
Unfortunately doesn't work well with Cygwin

### ISSUE THREAD

**Issue by hckr** [Xion/flappybash#1]
![flappybash](https://cloud.githubusercontent.com/assets/1078650/18001883/46fade16-6b85-11e6-9053-fe14db918864.png)

**Comment by Xion** [comment]
This looks like a terminal compatibility issue, making it not recognize some of the control ccodes. What does `echo $TERM` print? It should be either `xterm` or `xterm-256color`.

**Comment by hckr** [comment]
```
$ echo $TERM
xterm
```

Changing it in options to `xterm-256color` didn't help.

**Comment by Xion** [comment]
I just noticed this is a standard Windows "terminal emulator" which doesn't actually support the capabilities of `xterm`. You need something like mintty.
